allow-branch               = ["main", "maint-*"]
consolidate-commits        = true
pre-release-commit-message = "Namada {{version}}"
publish                    = false
push                       = false
shared-version             = true
tag                        = false
