[package]
name = "namada_storage"
description = "Namada ledger storage"
resolver = "2"
authors.workspace = true
edition.workspace = true
documentation.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = []
testing = [
    "namada_core/testing",
]
migrations = [
    "namada_migrations",
    "linkme",
]

[dependencies]
namada_core = { path = "../core" }
namada_gas = { path = "../gas" }
namada_macros = { path = "../macros" }
namada_merkle_tree = { path = "../merkle_tree" }
namada_migrations = {path = "../migrations", optional = true }
namada_replay_protection = { path = "../replay_protection" }
namada_tx = { path = "../tx" }

borsh.workspace = true
itertools.workspace = true
linkme = {workspace = true, optional = true}
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true
regex = "1.10.2"

[dev-dependencies]
namada_core = { path = "../core", features = ["testing"] }
