[package]
name = "namada_trans_token"
description = "Namada transparent token"
resolver = "2"
authors.workspace = true
edition.workspace = true
documentation.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = []
migrations = [
    "linkme"
]

[dependencies]
namada_core = { path = "../core" }
namada_storage = { path = "../storage" }

linkme = {workspace =  true, optional = true}

[dev-dependencies]
namada_storage = { path = "../storage", features = ["testing"] }
