[package]
name = "namada_token"
description = "Namada transparent and shielded token"
resolver = "2"
authors.workspace = true
edition.workspace = true
documentation.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = []
multicore = ["namada_shielded_token/multicore"]

[dependencies]
namada_core = { path = "../core" }
namada_shielded_token = { path = "../shielded_token" }
namada_storage = { path = "../storage" }
namada_trans_token = { path = "../trans_token" }
