allow-branch               = ["main", "maint-*"]
consolidate-commits        = true
pre-release-commit-message = "fixup! Namada {{version}}"
publish                    = false
push                       = false
shared-version             = true
tag                        = false
