[package]
name = "namada_proof_of_stake"
description = "Namada Proof of Stake system"
resolver = "2"
authors.workspace = true
edition.workspace = true
documentation.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = []
# testing helpers
testing = ["proptest"]
migrations = [
    "namada_migrations",
    "linkme",
]

[dependencies]
namada_account = { path = "../account" }
namada_core = { path = "../core" }
namada_governance = { path = "../governance" }
namada_macros = { path = "../macros" }
namada_migrations = { path = "../migrations", optional = true }
namada_storage = { path = "../storage" }
namada_parameters = { path = "../parameters" }
namada_trans_token = { path = "../trans_token" }

borsh.workspace = true
data-encoding.workspace = true
derivative.workspace = true
linkme = {workspace = true, optional = true}
num-traits.workspace = true
once_cell.workspace = true
proptest = { workspace = true, optional = true }
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true


[dev-dependencies]
namada_core = { path = "../core", features = ["testing"] }
namada_state = { path = "../state", features = ["testing"] }

assert_matches.workspace = true
itertools.workspace = true
proptest.workspace = true
proptest-state-machine.workspace = true
test-log.workspace = true
tracing-subscriber.workspace = true
pretty_assertions.workspace = true
derivative.workspace = true
yansi.workspace = true
