[package]
name = "namada_vote_ext"
description = "Namada vote extensions"
resolver = "2"
authors.workspace = true
edition.workspace = true
documentation.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[features]
migrations = [
    "namada_migrations",
    "linkme",
]

[dependencies]
namada_core = { path = "../core" }
namada_macros = { path = "../macros" }
namada_migrations = { path = "../migrations", optional = true }
namada_tx = { path = "../tx" }

borsh.workspace = true
linkme = {workspace = true, optional=true}
serde.workspace = true

[dev-dependencies]
namada_core = { path = "../core", features = ["testing"] }

data-encoding.workspace = true
